version: '3.4'
services:
 eshopwebmvc:
   image: regeshoponweb.azurecr.io/web22
   build:
      context: .
      dockerfile: src/Web/Dockerfile
   container_name: web
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5106:80"
   volumes:
     - ~/.aspnet/https:/root/.aspnet/https:ro
     - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
 eshoppublicapi:
   image: regeshoponweb.azurecr.io/api22
   build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
   container_name: api
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5200:80"
   volumes:
     - ~/.aspnet/https:/root/.aspnet/https:ro
     - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro